lab10/urls.py
from django.urls import path
from .views import *
# Create your views here.

app_name = 'lab10'
urlpatterns = [
	path('', landingRegisterAkun, name = 'landing'),
	path('submit/', registerAkun, name = 'reg'),
	path('validate-email/', validateEmail, name = 'validate'),
]

lab6/urls.py
from django.urls import path

from . import views

app_name = 'lab6'
urlpatterns = [
	path('', views.index, name='index'),
	path('add-status/', views.add_status, name='add_status'),
	path('home/', views.home, name='home'),
	path('getdata/', views.getdata, name='getdata'),
	path('buku/', views.show_buku, name='showbuku')
]

praktikum/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lab6.urls')),  
    path('lab10/', include('lab10.urls')),
]

lab10/models.py
from django.db import models

# Create your models here.
class Subscriber(models.Model):
	nama = models.CharField(max_length = 40)
	email = models.EmailField(max_length = 40, unique=True)
	password = models.CharField(max_length = 40)

lab6/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class status_model(models.Model):
    status = models.CharField(max_length=300)
    timenow = models.DateTimeField(default=timezone.now, blank=True)
    
        

lab10/forms.py
from django import forms
from .models import Subscriber
import datetime

class SubscriberForm(forms.Form):
	nama = forms.CharField(max_length = 40, widget = 
		forms.TextInput(attrs = {'id' : 'nama', 'class' : 'form-control', 'placeholder' : 'Nama', 'text-align' : 'center'}))
	email = forms.CharField(max_length = 40, widget = 
		forms.EmailInput(attrs = {'id' : 'email', 'class' : 'form-control', 'placeholder' : 'Email'}))
	password = forms.CharField(max_length = 40, widget = 
		forms.PasswordInput(attrs = {'id' : 'password', 'class' : 'form-control', 'placeholder' : 'Password'}))

lab10/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.db import IntegrityError
from .forms import SubscriberForm
from .models import Subscriber
import json

# Create your views here.
def landingRegisterAkun(request):
	response = {'form' : SubscriberForm}
	return render(request, "register.html", response)

def registerAkun(request):
	response = {}
	try:
	    if request.method == 'POST':
	        nama = request.POST.get('nama')
	        email = request.POST.get('email')
	        password = request.POST.get('password')
	        Subscriber.objects.create(nama=nama, email=email, password=password)
	        response['berhasil'] = True
	        response['pesan'] = 'Registrasi Berhasil'
	        json_data = json.dumps(response)
	        return HttpResponse(json_data)
	    else:
	        response['berhasil'] = False
	        response['pesan'] = 'Registrasi Gagal'
	        json_data = json.dumps(response)
	        return HttpResponse(json_data)
	except IntegrityError as e:
	    response['berhasil'] = False
	    response['pesan'] = 'Registrasi Gagal'
	    json_data = json.dumps(response)
	    return HttpResponse(json_data)
	
def validateEmail(request):
	response = {'pesan' : 'Email Valid', 'ada' : False}
	email = request.POST.get('email')
	response['ada'] = Subscriber.objects.filter(email=email).exists()
	if response['ada']:
	    response['pesan'] = 'Email Sudah Terdaftar'
	json_data = json.dumps(response)
	return HttpResponse(json_data)

lab6/views.py
import json
import requests
from django.shortcuts import render
from django.shortcuts import redirect
from django.http import JsonResponse
from .form import status_form
from .models import status_model

# Create your views here.
def index(request):    
    status = status_model.objects.all()
    form = status_form()
    html = 'index.html'
    return render(request, html, {'status' : status, 'form' : form})    

def home(request):
    response = {}
    return render(request, 'home.html', response)

def add_status(request):
    status = status_form(request.POST)
    if (request.method == 'POST' and status.is_valid()):
        temp = request.POST['status']
        status_model.objects.create(status=temp)

    return redirect('lab6:index')

def show_buku(request):
    return render(request, 'book.html', {});

def getdata(request):
    url = requests.get('https://www.googleapis.com/books/v1/volumes?q=quilting')
    jsons = url.json()
    return JsonResponse(jsons)

lab10/templates/register.html
{% load static %}
<html>
	<head>
		<!-- BOOSTRAP -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>   
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
        <link rel = "stylesheet" href = "https://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css">
        <link rel = "stylesheet" href = "{% static 'css/lab.css' %}">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
        <script src = "https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
        <script src = "{% static 'js/lab89.js' %}"></script>
		<title>Subscribe</title>
	</head>
	<body class = bg-light>
		<div class="loader"></div>
		<div class="bodypage" style="display: none;">
			{% include "navi.html" %}
			<div class = "container-fluid bg-white" >
				<div class = "row">
					<div class = "col-sm-4">
					</div>
					
					<div class = "col-sm-4">
						<br><br><br><br>
						<div class = "card bg-light" style = "margin: auto; width: 100%">
							<br>
							<h2 style = "font-family: 'Montserrat'; text-align: center; font-weight: bold;">
								FORM SUBSCRIBER
							</h2>

							<hr style = "border-color: #0086CD; border-width: 2px">
							<div class = "card-body">
								<form id= "form-subscriber" action = "#" method = 'POST'>
									{% csrf_token %}
									{{ form.as_p }}
									<br>
									<button type = "submit" class = "btn btn-block text-white" style = "background-color: #0086CD; font-family: 'Montserrat'; font-weight: bold; font-size: 20px" disabled="true">
										DAFTAR
									</button>
								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

		<script type="text/javascript">
			var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();
			var is_email_valid = false;

			function isValid(email) {
			    var regex = /^([a-zA-Z0-9_.+-])+\@(([a-zA-Z0-9-])+\.)+([a-zA-Z0-9]{2,4})+$/;
			    return regex.test(email);
			}

			function validasiInput() {
			    if ($('#nama').val() && $('#email').val() && $('#password').val() && is_email_valid) {
			        $('button[type=submit]').removeAttr('disabled');
			    } else {
			        $('button[type=submit]').attr('disabled', 'true');
			    }
			}

			function csrfSafeMethod(method) {
			    // these HTTP methods do not require CSRF protection
			    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
			}

			$(document).ready(function () {
			    $('#email').after("<div id='invalid_email' style='display: none' class='alert alert-danger alert-dismissible fade show' role='alert'></div>");
			    $('#email').after("<div id='valid_email' style='display: none' class='alert alert-success alert-dismissible fade show' role='alert'></div>");
			    $('button[type=submit]').after("<div id='failed' style='display: none' class='alert alert-danger' role='alert'></div>");
			    $('button[type=submit]').after("<div id='success' style='display: none' class='alert alert-success' role='alert'></div>");
			    $.ajaxSetup({
			        beforeSend: function(xhr, settings) {
			            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
			                xhr.setRequestHeader("X-CSRFToken", csrftoken);
			            }
			        }
			    });

			    $('#nama').on('change', function() {
			    	validasiInput();
			    });

			    $('#password').on('change', function() {
			    	validasiInput();
			    });

			    $('#email').on('change', function () {
		            var email = $(this).val();
		            $.ajax({
		                method: 'POST',
		                url: 'validate-email/',
		                data: {
		                    'email': email
		                },
		                dataType: 'json',
		                success: function (result) {
		                    var buttonClose = "<button type='button' " +
		                                      "class='close' data-dismiss='alert' aria-label='Close'>" +
		                                      "<span aria-hidden='true'>&times;</span></button>"
		                    if (isValid(email)) {
		                        if (result.ada) {
		                            $('#invalid_email').html(result.pesan + buttonClose);
		                            $('#invalid_email').css('display', 'block');
		                            $('#valid_email').css('display', 'none');
		                            $('#email').css('border-color', 'red');
		                            is_email_valid = false;
		                        } else {
		                            $('#valid_email').html(result.pesan + buttonClose);
		                            $('#valid_email').css('display', 'block');
		                            $('#invalid_email').css('display', 'none');
		                            $('#email').css('border-color', '#ced4da');
		                            is_email_valid = true;
		                        }
		                    } else {
		                        $('#invalid_email').html('Email tidak valid!' + buttonClose);
		                        $('#invalid_email').css('display', 'block');
		                        $('#valid_email').css('display', 'none');
		                        $('#email').css('border-color', 'red');
		                    }
							validasiInput();		                    
		                }
		            })
		        });

			    $('#form-subscriber').on('submit', function () {
			        var nama = $('#nama');
			        var email = $('#email');
			        var password = $('#password');
			        var data = {
			            'nama': nama.val(),
			            'email': email.val(),
			            'password': password.val(),
			        };
			        $.ajax({
			            method: 'POST',
			            url: 'submit/',
			            dataType: 'json',
			            data: data,
			            success: function (result) {
			                if (result.berhasil) {
			                    $('#success').html(result.pesan);
			                    $('#success').css('display', 'block');
			                    $('#failed').css('display', 'none');
			                    $('#valid_email').css('display', 'none');
			                    $('#invalid_email').css('display', 'none');
			                    nama.val("");
			                    email.val("");
			                    password.val("");
			                } else {
			                    $('#failed').html(result.pesan);
			                    $('#failed').css('display', 'block');
			                    $('#success').css('display', 'none');
			                    $('#valid_email').css('display', 'none');
			                    $('#invalid_email').css('display', 'none');
			                }
			            }
			        });
			        event.preventDefault();
			    });
			});
		</script>
	</body>
</html>

lab6/templates/book.html
{% load static %}
<html>
    <head>
        <!-- BOOTSTRAP -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>   
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
        <link rel = "stylesheet" href = "https://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css">
        <link rel = "stylesheet" href = "{% static 'css/lab.css' %}">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
        <script src = "https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
        <script src = "{% static 'js/lab89.js' %}"></script>

        <title>Book</title>
    </head>

    <body>
        <div class="loader"></div>
        <div class="bodypage" style="display: none; font-family: Consolas; text-align: center;">
            {% include "navi.html" %}
            <br>
            <h1 style="font-weight: bold;">
                DAFTAR BUKU
            </h1>
            <h5 id="cnt-favorit">
                JUMLAH BUKU FAVORIT : 0
            </h5>
            <br>
            <div class="container">
                <table class="table table-hover table-striped" align="center" style = "text-align : center" id="buku">
                    <thead>
                        <th>COVER BUKU</th>
                        <th>JUDUL</th>
                        <th>PENULIS</th>
                        <th>FAVORIT</th>
                    </thead>
                </table>
            </div>
        </div>

        <script type="text/javascript">
            var staroff = "{% static 'img/staroff.png' %}";
            var staron = "{% static 'img/staron.png' %}";
            var cnt = 0;

            var counter = 0;
            function favorit(id) {

                var objId = $('#' + id);
                var objImageSrc = objId[0].src;
                if (objImageSrc.includes('staroff')) {
                    cnt++;
                    objId[0].src = staron;
                } else {
                    cnt--;
                    objId[0].src = staroff;
                }
                $('#cnt-favorit').html('JUMLAH BUKU FAVORIT: ' + cnt);
            }   

            $(document).ready(function () {
                console.log("1");

                console.log("2");
                $.ajax({
                    url: '/getdata/',
                    success: function(obj) {
                        console.log("3");
                        var i;
                        for (i = 0; i < obj.items.length; i++) {
                            var judul = obj.items[i].volumeInfo.title;
                            var gambar = '<img id="zoom" src="' + obj.items[i].volumeInfo.imageLinks.thumbnail + '">';
                            var penulis = obj.items[i].volumeInfo.authors;
                            console.log(obj.items[i].id + " eaea " + i);
                            $('#buku').append('<tr><td>'+gambar+'</td><td>'+judul+'</td><td>'+ penulis+'</td><td><img class="imagess" onclick="' + 'favorit('+ "'" + obj.items[i].id + "'" + ')" id='+obj.items[i].id+ ' src=' + staroff + ' style="height:50px;"></td></tr>');

                        }
                    }

                }); 
            });

        </script>
        
    </body> 
</html>

lab6/templates/home.html
{% load static %}
<html>
	<head>
		<!-- BOOSTRAP -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>	
		<link rel = "stylesheet" href = "https://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css">
		<link rel = "stylesheet" href = "{% static 'css/lab.css' %}">
		<script src = "https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
		<script src = "{% static 'js/lab89.js' %}"></script>

		<title>Beranda</title>
	</head>

	<body>
		<div class="loader"></div>
		<div class="bodypage" style="display: none;">
			{% include "navi.html" %}
			<div class = "container-fluid">
				<div class = "row">
					<div class = "col-sm-4">
						<p style = "width : 100%; height : 3vw"></p>
						<div class = "row">
							<div class = "col-sm-1"></div>
							<div class = "col-sm-9">
								<img src = "{% static 'img/foto.jpg' %}" class = "img-fluid" alt = "Alfian Fuadi Rafli">
							</div>
						</div>
						
						<p style = "width : 100%; height : 2.7vw"></p>
						<div class = "row">
							<div class = "col-sm-1"></div>
							<div class = "col-sm-9">
								<a class="btn btn-primary btn-blocks btn-lg text-center" href = "https://drive.google.com/open?id=1urjl_SCXYwEWZyZgeNEgqi626AZD75l9" role="button" style = "width : 100%; font-size : 25; font-family : Consolas">UNDUH CV</a>
							</div>
						</div>
					</div>
					
					
					<div class = "col-sm-8">
						<div class = "ml-1">
							<p style = "width : 80%; height : 2.5vw"></p>
							<p style = "font-size : 40; font-family : Consolas">ALFIAN FUADI RAFLI
							<p style = "font-size : 25; font-family : Consolas">
								<br>Umur : 19
								<br>Alamat : Jl. Ambengan Batu II/31 Surabaya
								<br>No. Telefon : 082323779646
								<br>Email : alfianfuadi17@gmail.com
								<br>Website : alfianfuadi17.herokuapp.com
								<p style = "width : 80%; height : 7.5vw"></p>
								<div class = "row">
									<div class = "col-sm-2 text-center"><a href = "https://web.facebook.com/alfian.fuady.9?_rdc=1&_rdr"><img src = "{% static 'img/fb.png' %}" alt = "Facebook" style = "width : 50%; height : 70"></a></div>
									<br><br><br><br>
									<div class = "col-sm-2 text-center"><a href = "https://twitter.com/alfianfuady"><img src = "{%static 'img/twitter.png'%}" alt = "Twitter" style = "width : 50%; height : 70"></a></div>
									<br><br><br><br>
									<div class = "col-sm-2 text-center"><a href = "#"><img src = "{%static 'img/in.png'%}" alt = "Linkedin" style = "width : 50%; height : 70"></a></div>
									<br><br><br><br>
									<div class = "col-sm-2 text-center"><a href = "https://plus.google.com/100444775065017737259"><img src = "{%static 'img/ig.png'%}" alt = "Instagram" style = "width : 50%; height :70"></a></div>	
									<br><br><br><br>
									<div class = "col-sm-2 text-center"><a href = "https://www.instagram.com/alfianfuadi17/"><img src = "{%static 'img/g+.png'%}" alt = "Google Plus" style = "width : 50%; height : 70"></a></div>
								</div>
							</p>
						</div>
					</div>
				</div>
			
				<div class = "row">
					<div class = "col-sm-12	">
						<!--SUMBER : https://jqueryui.com/accordion/-->
						<div class = "accordion" style = "font-family: Consolas; font-size: 19"> 
							<h3>Aktivitas</h3>
							<div>
								<p>Kuliah</p>
							</div>
							<h3>Pengalaman</h3>
							<div>
								<p>Lulus DDP 1 dan 2</p>
							</div>
							<h3>Prestasi</h3>
							<div>
							    <p>Juara 2 Lomba Makan Kerupuk Tingkat Sekolah (2017)</p>
							</div>
						</div>
					</div>
				</div>
			</div>
			<br>
		</div>
	</body>
</html>		

lab6/templates/index.html
{% load static %}
<html>
    <head>
        <!-- BOOTSTRAP -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>   
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
        <link rel = "stylesheet" href = "https://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css">
        <link rel = "stylesheet" href = "{% static 'css/lab.css' %}">
        <script src = "https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
        <script src = "{% static 'js/lab89.js' %}"></script>

        <title>Status</title>
    </head>

    <body>
        <div class="loader"></div>
        <div class="bodypage" style="display: none;">
            {% include "navi.html" %}
            <br>
            <div class="container">
                <h1 style="text-align: center; font-family : Consolas" name="titlepage">Hello, Apa kabar?</h1>
                <hr>
                <h2 style="font-family : Consolas">Add Status</h2>
                <br>
                <form action={% url 'lab6:add_status' %} method="POST">
                    {% csrf_token %}    
                    {{ form.as_p }}
                    <button name = "statusbutton" type="submit" value="Submit">Submit</button>
                </form>	
                <br>
            </div>

            <div>
                {% if status|length > 0 %}
                    <div class="container">
                        <table class="table table-hover table-bordered table-striped" align="center" style = "text-align : center">
                            <thead style="text-align: center; font-family : Consolas; font-size: 23px">
                                <tr>
                                    <th scope="col" name="statustable">Status</th>
                                    <th scope="col" name="timetable">Time</th>
                                </tr>
                            </thead>
                            {% for data in status %}
                                <tr style="text-align: center; font-family : Consolas; font-size: 18px">
                                    <td scope="row" name="datastatus">{{ data.status }}</td>
                                    <td scope="row">{{ data.timenow }}</td>
                                </tr>
                            {% endfor %}
                        </table>
                    </div>
                {% else %}
               	 	<div class="container">
                    	<h1 style="text-align: center; font-family : Consolas">No Status</h1>
                	</div>
                {% endif %}
            </div>
            <br>
        </div>
    </body>	
</html>

lab6/templates/navi.html
{% load static %}
<nav class = "navbar navbar-expand-sm bg-light">
    <ul class="navbar-nav">
        <li class = "nav-item"> <div class = "ml-3"> <a style = "font-family : Consolas" class="nav-link text-body" href = "{% url 'lab6:home' %}">Beranda(Story 8)</a></div></li>
        <li class = "nav-item"> <div class = "ml-3"> <a style = "font-family : Consolas" class="nav-link text-body" href = "{% url 'lab6:index' %}">Status</a></div></li>
        <li class = "nav-item"> <div class = "ml-3"> <a style = "font-family : Consolas" class="nav-link text-body" href = "{% url 'lab6:showbuku' %}">Buku</a></div></li>
        <li class = "nav-item"> <div class = "ml-3"> <a style = "font-family : Consolas" class="nav-link text-body" href = "{% url 'lab10:landing' %}">Subscribe</a></div></li>
    </ul>

    <ul class="navbar-nav ml-auto">
        <button type="button" class="btn btn-primary tema" style = "font-family: Consolas; font-weight: bold">UBAH TEMA</button>
    </ul>

</nav>